### ISSUE TITLE
Add support for C4 DSL Language Server

### ISSUE THREAD

**Issue by Kiiv** [sebthom/extra-syntax-highlighting-eclipse-plugin#120]
Hi,

[C4 model](https://c4model.com/) is a great way to describe a software architecture.
A simple way to describe this kind of model is to use the [structurizr DSL](https://docs.structurizr.com/dsl).

There is a C4 DSL Language Server available here : https://gitlab.com/systemticks/c4-dsl-language-server

Do you think it should be possible to support this in Extra Syntax Highlighting plugin ?

**Comment by sebthom** [comment]
This repository only deals with TextMate files and not with LSPs. So while could try to add the grammar file from https://gitlab.com/systemticks/c4-grammar/-/blob/master/extension/syntaxes/c4.tmLanguage.json but it will only allow you to colorize the text files and does not provide auto-completion, refactoring etc. 

So you may be better of using the eclipse plugin found at https://gitlab.com/systemticks/c4-dsl-eclipse-plugin instead

**Comment by Kiiv** [comment]
Ok sorry for the mistake ! :)

I've found the plugin but because there is no description and few updates since first commit on the repo I tought it was non functional. I'll give it a try !
Thank you.
