### ISSUE TITLE
Custom file extension

### ISSUE THREAD

**Issue by ENate** [sebthom/extra-syntax-highlighting-eclipse-plugin#132]
Hi @sebthom Thanks for the awesome plugin. Will it be possible to extend your plugin to include other file extensions like ```.alloy```and similar extensions? Regards.

**Comment by sebthom** [comment]
Yes, additional file formats can be added if a textmate grammar is available on github.

**Comment by sebthom** [comment]
I didn't find a good syntax file for the alloy language. The only one that seems to work is https://github.com/DongyuZhao/vscode-alloy but the repository does not specify the license under which the files are released so I cannot include it.

I am going to close the issue for now. If you find a good textmate file for Alloy 6 please reopen.

**Comment by ENate** [comment]
Okay thanks for the info. Not so familiar with textmate but you bet..I will do so.
