### ISSUE TITLE
[Request] GLSL Support

### ISSUE THREAD

**Issue by Speiger** [sebthom/extra-syntax-highlighting-eclipse-plugin#59]
o/
Just found your plugin.
It is the only real big eclipse syntax highlighting plugin i found so far.
Sadly it doesn't provide what i wanted, but since it seems to be a "coverage" plugin, as in it tries to cover as much as possible.
I would like to request if you could add GLSL support too.

Tbh, i am not expecting you to do it but i thought, its worth a try asking.

**Comment by sebthom** [comment]
@Speiger I added the GLSL syntax file. Please update the plugin and give it a try.

**Comment by Speiger** [comment]
@sebthom thank you very much gonna try that right now.

**Comment by Speiger** [comment]
@sebthom small note. Your install guide doesn't work. The Gist has a 404.
Also the eclipse market place is like: Sorry but we can't find it.

**Comment by Speiger** [comment]
![image](https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin/assets/2556269/560563ee-0d02-460c-a9cc-f3bc9208dac8)

**Comment by sebthom** [comment]
Working fine for me:

![image](https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin/assets/426959/c247081c-3f77-4230-a8aa-1ca925ed1cd3)

![image](https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin/assets/426959/ed6c2b1a-7a58-447c-8a48-fbb2cc2568ff)

![image](https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin/assets/426959/942a6489-6cbc-4a62-a550-957e14fed718)

![image](https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin/assets/426959/d0b4a715-a40f-48cc-83f7-3c00f85e2a2b)

**Comment by Speiger** [comment]
Ok i had a dead URL somewhere in my sources. I cleaned that up and now it works just fine :)

Thank you.
Also the color choices are really good!
