### ISSUE TITLE
Please add support for mako template files

### ISSUE THREAD

**Issue by ZeeD** [sebthom/extra-syntax-highlighting-eclipse-plugin#76]
[Mako](https://www.makotemplates.org) is a template library written in Python.
Among other things, is used by [alembic](https://alembic.sqlalchemy.org/).
On https://github.com/sqlalchemy/mako/wiki#mako-syntax-highlighters there are already available some syntax highlighters, also for TextMate and Sublime Text, so it should be easy to extend this plugin to support the `.mako` extension.

**Comment by sebthom** [comment]
The textmate file linked at https://github.com/sqlalchemy/mako/wiki#mako-syntax-highlighters is unfortunately very outdated (2011) and broken. I now included the slightly better one from https://github.com/marconi/mako-tmbundle in https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin/commit/18960cb5a18a0adbaf3c5d197bbb8c2895c8d771 which however also doesn't seem to be maintained anymore and has open issues. so the syntax highlighting may not be fully functionally.
